name: midnight_oracle

include:
  - ../domain/docker-compose.yml

services:
  db:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    # Se a gente quiser a opção de deletar o container sem perder os dados
    # volumes:
    #   - postgres_devweb:/var/lib/postgresql/data
    env_file:
      - .env

  server:
    build: .
    ports:
      - "8910:8910"
    env_file:
      - .env

  squirrel:
    build: .
    profiles:
      - gen
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./src/
        target: /server/src
    command: ["-m", "squirrel"]

  cigogne:
    build: .
    profiles:
      - migrate
    env_file:
      - .env
    command: [ "-m", "cigogne", "all" ]
