FROM ghcr.io/gleam-lang/gleam:v1.16.0-erlang

WORKDIR /server

COPY gleam.toml manifest.toml ./
COPY src/ ./src/

RUN gleam deps download \
    && gleam build

CMD [ "gleam", "run", "-m", "squirrel" ]
